from __future__ import annotations

# Compatibility facade for legacy imports. The implementation lives in focused
# icon_* modules so legacy fallback readers stay isolated from the current
# image generation pipeline.

from .icon_candidates import (
    image_candidate_from_result,
    is_api_candidate,
    manifest_entry_is_fallback,
    saved_candidate_name,
    select_icon_manifest_candidate,
    selected_candidate_image_path,
)
from .icon_diagnostics import (
    API_ICON_RESOLUTION,
    image_api_summary,
    image_failure_diagnostics_from_reports,
    last_failure_class,
    last_image_api_failure,
    payload_secret_scan_status,
    report_value,
    skipped_image_report,
)
from .icon_pipeline import (
    DEFAULT_ICON_CANDIDATE_COUNT,
    DEFAULT_ICON_REGENERATION_CANDIDATE_COUNT,
    ICON_IMAGE_QUALITY_MODES,
    MAX_ICON_CANDIDATE_COUNT,
    collect_icon_style_reference,
    context_from_saved_proposal,
    generate_icon_assets,
    generate_icon_assets_with_candidates,
    generate_icon_candidates,
    icon_candidate_count,
    icon_design_brief_from_manifest,
    icon_image_generation_settings,
    icon_regeneration_candidate_count,
    list_from_import_plan,
    read_json_file,
    regenerate_icon_only,
    to_camel_key,
    update_icon_regeneration_timing,
    write_icon_regeneration_files,
    write_json_file,
    write_text_file,
)
from .icon_prompt import (
    ICON_CONCEPT_DIRECTIONS,
    ICON_REGENERATION_MODES,
    ICON_STYLE_PRESETS,
    build_icon_revision_api_base_prompt,
    deterministic_icon_concepts,
    extract_user_icon_request,
    generate_icon_concepts,
    icon_revision_concepts,
    icon_style_settings,
    image_api_prompt,
    infer_icon_style_preset,
    normalize_icon_revision_mode,
    normalize_icon_style_preset,
    parse_icon_concepts,
    revision_mode_policy,
    skipped_concept_report,
    user_directed_icon_concepts,
)
from .icon_quality import (
    candidate_quality_total,
    convert_png_row_to_rgba,
    decode_png_rows_rgba,
    dedupe_text,
    downsample_edge_score,
    estimate_visual_object_count,
    evaluate_icon_candidate_quality,
    extract_revision_instruction,
    generic_icon_risk_score,
    jaccard_similarity,
    meaningful_terms,
    paeth_predictor,
    png_dimensions,
    png_quality_metrics,
    quality_label,
    quantized_rgb,
    rgba_luminance,
    revision_follow_score,
    sampled_rgba_pixels,
    score_icon_candidate,
    unfilter_png_row,
    visible_bbox_ratio,
    apply_icon_candidate_quality,
)
from .openai_client import edit_image, generate_image
