from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from .models import LockGenerationResult, StudioContext
from .util import write_text


def generate_lock(context: StudioContext, requirements_path: Path, app_env_python: Path | None = None, skip: bool = False) -> LockGenerationResult:
    lock_path = requirements_path.parent / "requirements.lock"
    if skip:
        result = LockGenerationResult(True, True, lock_path, "skip", build_report(context, lock_path, "skip", ["Lock generation was skipped."]), "")
        write_lock_report(context, result)
        return result

    source_lock = context.source_root / "requirements.lock"
    if source_lock.is_file() and source_lock.resolve() != lock_path.resolve():
        lock_path.write_text(source_lock.read_text(encoding="utf-8", errors="replace"), encoding="utf-8")
        result = LockGenerationResult(True, False, lock_path, "existing requirements.lock", build_report(context, lock_path, "existing requirements.lock", [f"Copied existing lock file: {source_lock}"]), "")
        write_lock_report(context, result)
        return result

    notes = [
        "requirements.lock generated by ToolHub App Studio.",
        "pip freeze may include transitive or environment-specific packages. Review before release.",
    ]
    freeze_python = app_env_python if app_env_python and app_env_python.is_file() else None
    if freeze_python:
        completed = subprocess.run([str(freeze_python), "-m", "pip", "freeze"], cwd=str(context.repo_root), text=True, encoding="utf-8", errors="replace", stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
        notes.append(f"pip freeze used: {freeze_python}, exit_code={completed.returncode}")
        if completed.returncode == 0:
            lock_text = completed.stdout.strip() + ("\n" if completed.stdout.strip() else "")
            write_text(lock_path, lock_text)
            result = LockGenerationResult(True, False, lock_path, "pip freeze", build_report(context, lock_path, "pip freeze", notes), "")
            write_lock_report(context, result)
            return result
        notes.append("pip freeze failed; falling back to requirements.txt normalization.")

    if requirements_path.is_file():
        normalized = normalize_requirements(requirements_path)
        write_text(lock_path, "\n".join(normalized) + ("\n" if normalized else ""))
        notes.append(f"Normalized requirements source: {requirements_path}")
        result = LockGenerationResult(True, False, lock_path, "requirements.txt normalization", build_report(context, lock_path, "requirements.txt normalization", notes), "")
        write_lock_report(context, result)
        return result

    write_text(lock_path, "")
    notes.append("No requirements.txt was present; an empty lock file was created.")
    result = LockGenerationResult(True, False, lock_path, "empty", build_report(context, lock_path, "empty", notes), "")
    write_lock_report(context, result)
    return result


def normalize_requirements(path: Path) -> list[str]:
    lines: list[str] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            lines.append(stripped)
    return lines


def build_report(context: StudioContext, lock_path: Path, source: str, notes: list[str]) -> str:
    lines = [
        "# Lock Generation Report",
        "",
        f"- app_id: `{context.app_id}`",
        f"- lock_path: `{lock_path}`",
        f"- source: `{source}`",
        f"- python: `{sys.executable}`",
        "",
        "## Notes",
        "",
    ]
    lines.extend(f"- {note}" for note in notes)
    return "\n".join(lines) + "\n"


def write_lock_report(context: StudioContext, result: LockGenerationResult) -> None:
    write_text(context.output_dir / "lock_generation_report.md", result.report)
    write_text(context.repo_root / "data" / "logs" / "app_studio" / f"{context.app_id}_lock_generation_report.md", result.report)

