from __future__ import annotations

from .models import BuildPlan, StudioContext


def generate_readme(context: StudioContext, plan: BuildPlan) -> str:
    lines = [
        f"# {context.name}",
        "",
        "This app definition was generated by ToolHub App Studio.",
        "",
        "## ToolHub Registration",
        "",
        f"- App ID: `{context.app_id}`",
        f"- Version: `{context.version}`",
        f"- Build mode: `{plan.mode}`",
        f"- Runner: `{plan.runner}`",
        f"- Entry: `{plan.entry}`",
        "",
        "## Approval",
        "",
        "This app starts with `enabled=false` in `release/app_manifest.json`.",
        "Run the approval command after reviewing the generated files and execution test report.",
    ]
    if plan.warnings:
        lines.extend(["", "## Notes", ""])
        lines.extend(f"- {warning}" for warning in plan.warnings)
    return "\n".join(lines) + "\n"

